require 'git2'

require 'simple_git/commit'
require 'simple_git/diff'
require 'simple_git/diff_options'
require 'simple_git/diff_stat'
require 'simple_git/oid'
require 'simple_git/repository'
require 'simple_git/revwalk'
require 'simple_git/signature'
require 'simple_git/tree'
